_dataset_map = {
    "data": "data",
    "ZTT": "DY",
    "ZL": "DY",
    "ZJ": "DY",
    "ZTT_NLO": "DYNLO",
    "ZL_NLO": "DYNLO",
    "ZJ_NLO": "DYNLO",
    "TTT": "TT",
    "TTL": "TT",
    "TTJ": "TT",
    "VVT": "VV",
    "VVL": "VV",
    "VVJ": "VV",
    "EMB": "EMB",
    "W": "W",
    "W_NLO": "WNLO",
    "qqH125": "qqH",
    "ZH125": "ZH",
    "WH125": "WH",
}

_process_map = {
    "data": "data",
    "ZTT": "DY-ZTT",
    "ZL": "DY-ZL",
    "ZJ": "DY-ZJ",
    "ZTT_NLO": "DY_NLO-ZTT",
    "ZL_NLO": "DY_NLO-ZL",
    "ZJ_NLO": "DY_NLO-ZJ",
    "TTT": "TT-TTT",
    "TTL": "TT-TTL",
    "TTJ": "TT-TTJ",
    "VVT": "VV-VVT",
    "VVL": "VV-VVL",
    "VVJ": "VV-VVJ",
    "EMB": "Embedded",
    "W": "W",
    "W_NLO": "W",
    "qqH125": "qqH125",
    "ZH125": "ZH125",
    "WH125": "WH125",
}

_name_string = "{dataset}#{channel}{process}{selection}#{variation}#{variable}"